//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Share {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Share() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Share", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity log.
        /// </summary>
        internal static string ActivityLog {
            get {
                return ResourceManager.GetString("ActivityLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add accessory page.
        /// </summary>
        internal static string AddAccessoryPage {
            get {
                return ResourceManager.GetString("AddAccessoryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add admin.
        /// </summary>
        internal static string AddAdmin {
            get {
                return ResourceManager.GetString("AddAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add brand.
        /// </summary>
        internal static string AddBrand {
            get {
                return ResourceManager.GetString("AddBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add existed user.
        /// </summary>
        internal static string AddExistedUser {
            get {
                return ResourceManager.GetString("AddExistedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add exist page sequence.
        /// </summary>
        internal static string AddExistPageSequence {
            get {
                return ResourceManager.GetString("AddExistPageSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add help item.
        /// </summary>
        internal static string AddHelpItem {
            get {
                return ResourceManager.GetString("AddHelpItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New intervent.
        /// </summary>
        internal static string AddIntervent {
            get {
                return ResourceManager.GetString("AddIntervent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New intervent category.
        /// </summary>
        internal static string AddInterventCategory {
            get {
                return ResourceManager.GetString("AddInterventCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new page sequence.
        /// </summary>
        internal static string AddNewPageSequence {
            get {
                return ResourceManager.GetString("AddNewPageSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new page sequence base on exist.
        /// </summary>
        internal static string AddNewPageSequenceBaseOnExist {
            get {
                return ResourceManager.GetString("AddNewPageSequenceBaseOnExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New page.
        /// </summary>
        internal static string AddPage {
            get {
                return ResourceManager.GetString("AddPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New page sequence.
        /// </summary>
        internal static string AddPageSequence {
            get {
                return ResourceManager.GetString("AddPageSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New predictor.
        /// </summary>
        internal static string AddPredictor {
            get {
                return ResourceManager.GetString("AddPredictor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New predictor category.
        /// </summary>
        internal static string AddPredictorCategory {
            get {
                return ResourceManager.GetString("AddPredictorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New program.
        /// </summary>
        internal static string AddProgram {
            get {
                return ResourceManager.GetString("AddProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddProgramRoom {
            get {
                return ResourceManager.GetString("AddProgramRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New session.
        /// </summary>
        internal static string AddSession {
            get {
                return ResourceManager.GetString("AddSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New status.
        /// </summary>
        internal static string AddStatus {
            get {
                return ResourceManager.GetString("AddStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program manager system.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application user security.
        /// </summary>
        internal static string ApplicationSecurity {
            get {
                return ResourceManager.GetString("ApplicationSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back-office.
        /// </summary>
        internal static string Backoffice {
            get {
                return ResourceManager.GetString("Backoffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changetech.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of pages.
        /// </summary>
        internal static string CountOfPages {
            get {
                return ResourceManager.GetString("CountOfPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTD Log.
        /// </summary>
        internal static string CTDLog {
            get {
                return ResourceManager.GetString("CTDLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit accessory page.
        /// </summary>
        internal static string EditAccessoryPage {
            get {
                return ResourceManager.GetString("EditAccessoryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit brand.
        /// </summary>
        internal static string EditBrand {
            get {
                return ResourceManager.GetString("EditBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit help item.
        /// </summary>
        internal static string EditHelpItem {
            get {
                return ResourceManager.GetString("EditHelpItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit intervent.
        /// </summary>
        internal static string EditIntervent {
            get {
                return ResourceManager.GetString("EditIntervent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit intervent category.
        /// </summary>
        internal static string EditInterventCategory {
            get {
                return ResourceManager.GetString("EditInterventCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit page.
        /// </summary>
        internal static string EditPage {
            get {
                return ResourceManager.GetString("EditPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit page sequence.
        /// </summary>
        internal static string EditPageSequence {
            get {
                return ResourceManager.GetString("EditPageSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit predictor.
        /// </summary>
        internal static string EditPredictor {
            get {
                return ResourceManager.GetString("EditPredictor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit predictor category.
        /// </summary>
        internal static string EditPredictorCategory {
            get {
                return ResourceManager.GetString("EditPredictorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        internal static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit program.
        /// </summary>
        internal static string EditProgram {
            get {
                return ResourceManager.GetString("EditProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditProgramRoom {
            get {
                return ResourceManager.GetString("EditProgramRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit session.
        /// </summary>
        internal static string EditSession {
            get {
                return ResourceManager.GetString("EditSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit status.
        /// </summary>
        internal static string EditStatus {
            get {
                return ResourceManager.GetString("EditStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update translation.
        /// </summary>
        internal static string EditTranslation {
            get {
                return ResourceManager.GetString("EditTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user menu.
        /// </summary>
        internal static string EditUserMenu {
            get {
                return ResourceManager.GetString("EditUserMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmailTemplate {
            get {
                return ResourceManager.GetString("EmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Log.
        /// </summary>
        internal static string ErrorLog {
            get {
                return ResourceManager.GetString("ErrorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changetech© Digital Therapy Developer© {0} v 2.643.
        /// </summary>
        internal static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General class.
        /// </summary>
        internal static string GeneralClass {
            get {
                return ResourceManager.GetString("GeneralClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to add intervent page.
        /// </summary>
        internal static string GoAddIntervent {
            get {
                return ResourceManager.GetString("GoAddIntervent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to add predictor page.
        /// </summary>
        internal static string GoAddPredictor {
            get {
                return ResourceManager.GetString("GoAddPredictor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to add predictor category page.
        /// </summary>
        internal static string GoAddPredictorCategory {
            get {
                return ResourceManager.GetString("GoAddPredictorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to add program page.
        /// </summary>
        internal static string GoAddProgram {
            get {
                return ResourceManager.GetString("GoAddProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to add session page.
        /// </summary>
        internal static string GoAddSession {
            get {
                return ResourceManager.GetString("GoAddSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to add specific intervent page.
        /// </summary>
        internal static string GoAddSpecificIntervent {
            get {
                return ResourceManager.GetString("GoAddSpecificIntervent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to application security page.
        /// </summary>
        internal static string GoApplicationSecurity {
            get {
                return ResourceManager.GetString("GoApplicationSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to edit specific intervent.
        /// </summary>
        internal static string GoEditIntervent {
            get {
                return ResourceManager.GetString("GoEditIntervent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to edit intervent category page.
        /// </summary>
        internal static string GoEditInterventCategory {
            get {
                return ResourceManager.GetString("GoEditInterventCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to edit page sequence page.
        /// </summary>
        internal static string GoEditPageSequence {
            get {
                return ResourceManager.GetString("GoEditPageSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to edit predictor page.
        /// </summary>
        internal static string GoEditPredictor {
            get {
                return ResourceManager.GetString("GoEditPredictor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to edit predictor category page.
        /// </summary>
        internal static string GoEditPredictorCategory {
            get {
                return ResourceManager.GetString("GoEditPredictorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to edit program page.
        /// </summary>
        internal static string GoEditProgram {
            get {
                return ResourceManager.GetString("GoEditProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to edit session page.
        /// </summary>
        internal static string GoEditSession {
            get {
                return ResourceManager.GetString("GoEditSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to home page.
        /// </summary>
        internal static string GoHome {
            get {
                return ResourceManager.GetString("GoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to intervent management page.
        /// </summary>
        internal static string GoIntervent {
            get {
                return ResourceManager.GetString("GoIntervent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to intervent category management page.
        /// </summary>
        internal static string GoInterventCategory {
            get {
                return ResourceManager.GetString("GoInterventCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to order email template page.
        /// </summary>
        internal static string GoOrderEmailTemplate {
            get {
                return ResourceManager.GetString("GoOrderEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to predictor management page.
        /// </summary>
        internal static string GoPredictor {
            get {
                return ResourceManager.GetString("GoPredictor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to predictor category manangement page.
        /// </summary>
        internal static string GoPredictorCategory {
            get {
                return ResourceManager.GetString("GoPredictorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to programs list.
        /// </summary>
        internal static string GoPrograms {
            get {
                return ResourceManager.GetString("GoPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to program security page.
        /// </summary>
        internal static string GoProgramSecurity {
            get {
                return ResourceManager.GetString("GoProgramSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to program status management page.
        /// </summary>
        internal static string GoProgramStatus {
            get {
                return ResourceManager.GetString("GoProgramStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help item.
        /// </summary>
        internal static string HelpItem {
            get {
                return ResourceManager.GetString("HelpItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive User.
        /// </summary>
        internal static string InactiveUser {
            get {
                return ResourceManager.GetString("InactiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervent.
        /// </summary>
        internal static string Intervent {
            get {
                return ResourceManager.GetString("Intervent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervent category.
        /// </summary>
        internal static string InterventCategory {
            get {
                return ResourceManager.GetString("InterventCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated by.
        /// </summary>
        internal static string LastUpdateBy {
            get {
                return ResourceManager.GetString("LastUpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed in as.
        /// </summary>
        internal static string LoginAs {
            get {
                return ResourceManager.GetString("LoginAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login User.
        /// </summary>
        internal static string LoginUser {
            get {
                return ResourceManager.GetString("LoginUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Priority.
        /// </summary>
        internal static string LogPriority {
            get {
                return ResourceManager.GetString("LogPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Type.
        /// </summary>
        internal static string LogType {
            get {
                return ResourceManager.GetString("LogType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make copy.
        /// </summary>
        internal static string MakeCopy {
            get {
                return ResourceManager.GetString("MakeCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        internal static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage CTPP.
        /// </summary>
        internal static string ManageCTPP {
            get {
                return ResourceManager.GetString("ManageCTPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DailyReportSMS.
        /// </summary>
        internal static string ManageDailyReportSMS {
            get {
                return ResourceManager.GetString("ManageDailyReportSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage status.
        /// </summary>
        internal static string ManageProgramStatus {
            get {
                return ResourceManager.GetString("ManageProgramStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Job.
        /// </summary>
        internal static string ManageTranslationJob {
            get {
                return ResourceManager.GetString("ManageTranslationJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts management.
        /// </summary>
        internal static string ManageUser {
            get {
                return ResourceManager.GetString("ManageUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User menu.
        /// </summary>
        internal static string ManageUserMenu {
            get {
                return ResourceManager.GetString("ManageUserMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed Class User.
        /// </summary>
        internal static string MissedClassUser {
            get {
                return ResourceManager.GetString("MissedClassUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page sequence.
        /// </summary>
        internal static string MovePageSequence {
            get {
                return ResourceManager.GetString("MovePageSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New application user.
        /// </summary>
        internal static string NewApplicationUser {
            get {
                return ResourceManager.GetString("NewApplicationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New program user.
        /// </summary>
        internal static string NewProgramUser {
            get {
                return ResourceManager.GetString("NewProgramUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user.
        /// </summary>
        internal static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (This program is published, you cannot change it. If you want to change, please switch its status to &quot;Under Development&quot;.).
        /// </summary>
        internal static string NotChangeableBecauseOfPublished {
            get {
                return ResourceManager.GetString("NotChangeableBecauseOfPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderEmailTemplate.
        /// </summary>
        internal static string OrderEmailTemplate {
            get {
                return ResourceManager.GetString("OrderEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page review.
        /// </summary>
        internal static string PageReview {
            get {
                return ResourceManager.GetString("PageReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq.
        /// </summary>
        internal static string PageSequence {
            get {
                return ResourceManager.GetString("PageSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Variable.
        /// </summary>
        internal static string PageVariable {
            get {
                return ResourceManager.GetString("PageVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reminder.
        /// </summary>
        internal static string PasswordReminder {
            get {
                return ResourceManager.GetString("PasswordReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictor.
        /// </summary>
        internal static string Predictor {
            get {
                return ResourceManager.GetString("Predictor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictor category.
        /// </summary>
        internal static string PredictorCategory {
            get {
                return ResourceManager.GetString("PredictorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string PreviewPage {
            get {
                return ResourceManager.GetString("PreviewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program accessory.
        /// </summary>
        internal static string ProgramAccessory {
            get {
                return ResourceManager.GetString("ProgramAccessory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program class.
        /// </summary>
        internal static string ProgramClass {
            get {
                return ResourceManager.GetString("ProgramClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Room.
        /// </summary>
        internal static string ProgramRoom {
            get {
                return ResourceManager.GetString("ProgramRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs.
        /// </summary>
        internal static string Programs {
            get {
                return ResourceManager.GetString("Programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program status.
        /// </summary>
        internal static string ProgramStatus {
            get {
                return ResourceManager.GetString("ProgramStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Security.
        /// </summary>
        internal static string ProgramUser {
            get {
                return ResourceManager.GetString("ProgramUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project manager.
        /// </summary>
        internal static string ProjectManager {
            get {
                return ResourceManager.GetString("ProjectManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psybase.
        /// </summary>
        internal static string Psybase {
            get {
                return ResourceManager.GetString("Psybase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered User.
        /// </summary>
        internal static string RegisteredUser {
            get {
                return ResourceManager.GetString("RegisteredUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session ending.
        /// </summary>
        internal static string SessionEnding {
            get {
                return ResourceManager.GetString("SessionEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Azure.
        /// </summary>
        internal static string SQLAzure {
            get {
                return ResourceManager.GetString("SQLAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status management.
        /// </summary>
        internal static string StatusManagement {
            get {
                return ResourceManager.GetString("StatusManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Log.
        /// </summary>
        internal static string SystemLog {
            get {
                return ResourceManager.GetString("SystemLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program setting.
        /// </summary>
        internal static string TemplateSetting {
            get {
                return ResourceManager.GetString("TemplateSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip message.
        /// </summary>
        internal static string TipMessage {
            get {
                return ResourceManager.GetString("TipMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        internal static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update password.
        /// </summary>
        internal static string UpdatePassword {
            get {
                return ResourceManager.GetString("UpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update user.
        /// </summary>
        internal static string UpdateUser {
            get {
                return ResourceManager.GetString("UpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used in programs.
        /// </summary>
        internal static string UsedInPrograms {
            get {
                return ResourceManager.GetString("UsedInPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Log.
        /// </summary>
        internal static string UserLog {
            get {
                return ResourceManager.GetString("UserLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts management.
        /// </summary>
        internal static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program User Security.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
